"""empty message

Revision ID: 438caca0e6d9
Revises: e379c0f79bbf
Create Date: 2024-10-01 20:24:24.817122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438caca0e6d9'
down_revision = 'e379c0f79bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=130),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=130),
               existing_nullable=False)

    # ### end Alembic commands ###
